CREATE TABLE CUSTOMER (
  C_ID VARCHAR(100) NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  MOBILE_NUM VARCHAR(100),
  ADDRESS VARCHAR(100),
  GENDER VARCHAR(100),
  DOB DATETIME,
  DATE_OF_REG DATETIME,
  POSTAL_CODE VARCHAR(100),
  PRIMARY KEY (C_ID)
);

CREATE TABLE FACILITY (
  FACILITY_ID VARCHAR(100) NOT NULL,
  FACILITY_DESC VARCHAR(1000),
  FACILITY_TYPE VARCHAR(100),
  FACILITY_CAPACITY INT,
  FACILITY_SUBTYPE VARCHAR(1000),
  LOCATION VARCHAR(100),
  PRIMARY KEY (FACILITY_ID)
);

CREATE TABLE PAYMENT_METHOD (
  PAYMENT_METHOD_ID INT NOT NULL,
  PAYMENT_METHOD_DESC VARCHAR(100),
  PRIMARY KEY (PAYMENT_METHOD_ID)
);

CREATE TABLE PAYMENT (
  PAYMENT_ID INT NOT NULL,
  PAYMENT_METHOD_ID INT,
  PROMO_APPLIED INT(1),
  PRICE INT,
  PURCHASE_MODE VARCHAR(100),
  PRIMARY KEY (PAYMENT_ID),
  FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

CREATE TABLE TICKET_CATEGORY (
  CATEGORY_TICKET_ID INT(1) NOT NULL,
  CATEGORY_TICKET_DESC VARCHAR(100),
  PRIMARY KEY (CATEGORY_TICKET_ID)
);

CREATE TABLE RIDE (
  RIDE_ID VARCHAR(100) NOT NULL,
  RIDE_NAME VARCHAR(100),
  TYPE_OF_RIDE VARCHAR(100),
  CAPACITY_OF_A_RIDE INT,
  RIDE_HEIGHT INT,
  YEARS_STARTED YEAR(4),
  DESCRIPTION VARCHAR(10000),
  MIN_RIDE_HEIGHT VARCHAR(1000),
   MANUFACTURER VARCHAR(100),
  `TOP_SPEED(MPH)` FLOAT,
  `TRACK_LENGTH(FT)` FLOAT,
  ADDITIONAL_FEES VARCHAR(1),
  PRIMARY KEY (RIDE_ID)
);

CREATE TABLE TICKET (
  TICKET_ID INT NOT NULL,
  C_ID VARCHAR(100),
  PAYMENT_ID INT NOT NULL,
  CATEGORY_TICKET_ID INT(1),
  PRIMARY KEY (TICKET_ID, C_ID, PAYMENT_ID, CATEGORY_TICKET_ID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
  FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
  FOREIGN KEY (CATEGORY_TICKET_ID) REFERENCES TICKET_CATEGORY(CATEGORY_TICKET_ID)
);

CREATE TABLE TICKET_RIDE(
TICKET_ID INT,
RIDE_ID VARCHAR(100),
TIMESTAMP TIMESTAMP,
PRIMARY KEY (TICKET_ID, RIDE_ID, TIMESTAMP),
FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID),
FOREIGN KEY (RIDE_ID) REFERENCES RIDE(RIDE_ID)
); 

CREATE TABLE TICKET_FACILITY(
TICKET_ID INT,
FACILITY_ID VARCHAR(100),
TIMESTAMP TIMESTAMP,
PRIMARY KEY (TICKET_ID, FACILITY_ID, TIMESTAMP),
FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID),
FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY(FACILITY_ID)
); 





